analyzer:
  exclude:
    - 'lib/**.g.dart'
    - 'lib/l10n/**.dart'
    - 'lib/routes/**.dart'

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # https://github.com/dart-lang/linter/blob/master/example/all.yaml
    close_sinks: true
    only_throw_errors: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    valid_regexps: true
    use_build_context_synchronously: false
