name: human_id
description: HumanID application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  live_detection_plugin:
    path: ../live_detection_plugin

  flutter_svg: ^1.1.6
  flutter_displaymode: ^0.4.1
  flutter_markdown: ^0.6.13
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  permission_handler: ^10.2.0
  device_info_plus: ^8.0.0
  package_info_plus: ^3.0.2
  ff_annotation_route_library: ^3.0.0
  lottie: ^2.0.0
  local_auth: ^2.1.2
  modal_bottom_sheet: ^2.1.2
  mlkit_scan_plugin:
    git:
      url: https://github.com/fluttercandies/flutter_mlkit_scan_plugin
      ref: "3665c0ea"
  oktoast: ^3.3.1
  sliver_tools: ^0.2.8
  url_launcher: ^6.1.7
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.1
  functional_widget_annotation: ^0.10.0
  flutter_secure_storage: ^6.1.0
  path_provider: ^2.0.11
  intl: ^0.17.0
  collection: ^1.16.0
  carousel_slider: ^4.1.1
  tuple: ^2.0.1
  extended_sliver: ^2.1.3
  image_picker: ^0.8.6
  web3dart: 2.4.1
  http: ^0.13.5
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  hive_generator: ^2.0.0
  process_run: ^0.12.3+2
  functional_widget: ^0.10.1
  yaml: ^3.1.1
  flutter_gen_runner: ^5.1.0+1
  flutter_lints: ^2.0.1
  web3dart_builders: ^0.0.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/icons/guide/
    - assets/icons/about/
    - assets/icons/qrscan/
  fonts:
    - family: "Gotham"
      fonts:
        - asset: assets/fonts/Gotham-Bold.otf
          weight: 700
    - family: "PT Sans"
      fonts:
        - asset: assets/fonts/PT-Sans.ttf
        - asset: assets/fonts/PT-Sans-Bold.ttf
          weight: 700

flutter_gen:
  output: lib/res
  line_length: 80
  integrations:
    flutter_svg: true


